version: "3"

services:
  # FastApi
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    # FastAPIを8000ポートで待機
    command: ["pipenv", "run", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./app/:/usr/src/app
